# =========================================================
# APPLICATION
# =========================================================

spring.application.name=travelgo-api-gateway
server.port=8080


# =========================================================
# EUREKA CLIENT
# =========================================================

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost


# =========================================================
# JWT
# =========================================================

jwt.secret-key=CcjhxV/QsZwWhtCR2J0BxkP5myQ9MhjQqHQtcanHNkg=

# =========================================================
# AUTH SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://TRAVELGO-AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**


# =========================================================
# PROPERTY SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[1].id=property-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://TRAVELGO-PROPERTY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/properties/**


# =========================================================
# ROOM APIs
# Room APIs are inside Property Service
# =========================================================

spring.cloud.gateway.server.webflux.routes[2].id=property-service-rooms
spring.cloud.gateway.server.webflux.routes[2].uri=lb://TRAVELGO-PROPERTY-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/rooms/**


# =========================================================
# BOOKING SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[3].id=booking-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://TRAVELGO-BOOKING-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/bookings/**